FROM python:3.9-slim-buster

WORKDIR /usr/src/app

COPY apps/scheduler/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY apps/scheduler/src ./src

ENV PYTHONUNBUFFERED=1
CMD ["python", "src/main.py"]
